### PR TITLE
drop laminas/laminas-console

### PR DESCRIPTION
**Pull request by fezfez**
Signed-off-by: Stéphane Demonchaux <demonchaux.stephane@gmail.com>

|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      | yes
| New Feature   | no
| RFC           | no
| QA            | no

### Description

Must target 4.0.x but the branch does not exist yet.

### CODE REVIEW

**Review by snapshotpl — APPROVED** [review]
Since laminas-console is deprecated this PR is very welcome.

**Comment by FabianKoestring** [comment]
> Since laminas-console is deprecated this PR is very welcome.

Yes it is!

**Comment by snapshotpl** [comment]
@fezfez please resolve conflicts first

**Comment by fezfez** [comment]
@snapshotpl done !

**Comment by fezfez** [comment]
@snapshotpl : i have re generate psalm baseline because it complain about "`ExpectationFailedException` is internal to PHPUnit" and it's not related to this PR.

**Comment by adamdyson** [comment]
🤞this gets merged soon

**Comment by snapshotpl** [comment]
Fixes #16

**Pull request merged**
