### PR TITLE
New method: assertRedirectToRoute 

### LINKED ISSUE #2: New method: assertRedirectToRoute for more robust redirect checks in tests
- [x] I was not able to find an [open](https://github.com/zendframework/zend-test/issues?q=is%3Aopen) or [closed](https://github.com/zendframework/zend-test/issues?q=is%3Aclosed) issue matching what I'm seeing.
- [x] This is not a question. (Questions should be asked on [slack](https://zendframework.slack.com/) ([Signup for Slack here](https://zendframework-slack.herokuapp.com/)) or our [forums](https://discourse.zendframework.com/).)

Would it be nice to have a new `assertRedirectToRoute` method for easier checking of redirects? In opposite to `assertRedirectTo`, the new method would be more robust due to changes in the routes of the application to test.

F.e. if I change the URI in one of the routes (`my-route`) of my application from `/foo/bar/baz` to `/foo-foo/bar-bar/baz-baz`, I would have to modify my test case too:

```php
...
$this->assertRedirectTo('/foo/bar/baz');
...
```
to 

```php
...
$this->assertRedirectTo('/foo-foo/bar-bar/baz-baz');
...
```
---

With the new method:

```php
...
$this->assertRedirectToRoute('my-route');
...
```

What do you think? I could make a pull-request for that if you would accept my proposal.

---

Originally posted by @koseduhemak at https://github.com/zendframework/zend-test/issues/68

### PR DESCRIPTION
**Pull request by nusphere**
... for more robust redirect checks in tests

|    Q          |   A
|-------------- | ------
| Documentation | yes
| New Feature   | yes

### Description

As descripted in #2 - this PR will provide this new method.

closes #2

### CODE REVIEW

**Comment by nusphere** [comment]
As already described in issue #6, the current way for the custom laminas assertions is not the recommended way by PHPUnit.

I have created a contraint for this, which adheres to the recommendations of PHPUnit.

**Comment by Xerkus** [comment]
@nusphere please rebase your PRs. Base branch had CI setup updated

**Comment by nusphere** [comment]
I will solve this tomorrow

**Comment by nusphere** [comment]
thank you

**Pull request merged**
