### PR TITLE
Removed unused `laminas/laminas-log` dependency

### PR DESCRIPTION
**Pull request by gsteel**
|    Q          |   A
|-------------- | ------
| QA            | yes

### Description

Saw this while reading https://github.com/laminas/technical-steering-committee/issues/68

Removes `laminas-log` along with other minor chores.

### CODE REVIEW

**Review by Ocramius — APPROVED** [review]
LGTM 👍

**Comment by froschdesign** [comment]
@gsteel 
I think pull requests like these needs a better title because now we have the following in the release notes:

> 60: Remove laminas log thanks to @gsteel

But what does this means for the end user? 

- Has the logging feature been removed?
- Does the user have to do or change anything?
- What is the background of the change?
- Or is there an alternative?

In the current case, nothing at all needs to be done, as an unused component has been removed. But this is not clear from the release notes or this pull request.

(The description of a milestone can also be used to add a detailed explanation, which is displayed in the release notes.)

**Comment by gsteel** [comment]
> I think pull requests like these needs a better title because now we have the following in the release notes:

Good point @froschdesign - Duly noted 👍

**Comment by Ocramius** [comment]
@froschdesign updated PR title and release notes - sorry, multitasking from the phone :|

**Pull request merged**
