### PR TITLE
Fixes wrong module name recognation in 3.5.0

### LINKED ISSUE #34: Module name is not recognized correctly in 3.5.0
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 3.5.0

#### Summary

It looks like the changes in #21 don't really work.

#### Current behavior

We have a controller `Praktikumsangebot` in Module `Angebote` and Namespace `Angebote\Controller`. In a test we check with `$this->assertModuleName('Angebote');` if the module is `Angebote`. We also have a module `Praktikum`. In versions prior `3.5.0` the tests pass.

I checked `getCurrentModuleName()` in `IsCurrentModuleNameConstraint`. In version `3.5.0` it will return `praktikum`.

### PR DESCRIPTION
**Pull request by FabianKoestring**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | yes
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | yes

### Description
fixes #34 
Fixes a bug introduced in 3.5.0. In some cases module names were not recognized correctly.

ping @nusphere

### CODE REVIEW

**Comment by FabianKoestring** [comment]
@nusphere Having problems again.... 

Module A: `DualesStudium`
Module B: `Studium`
Controller Class: `DualesStudium\Controller\DualesStudium`

`$this->assertModuleName('DualesStudium')` will return `false`.

**Review by snapshotpl — APPROVED** [review]
This is fine. However I would like to see falling test (or fix) for comment https://github.com/laminas/laminas-test/pull/36#issuecomment-872812220 by @FabianKoestring

**Comment by FabianKoestring** [comment]
> This is fine. However I would like to see falling test (or fix) for comment [#36 (comment)](https://github.com/laminas/laminas-test/pull/36#issuecomment-872812220) by @FabianKoestring

I have no working php7 at the moment. I could take a look at it but only against branch 4.0.

**Comment by snapshotpl** [comment]
OK, I think it's not a blocker for release. We can make new one

**Pull request merged**
